In [ ]:
# importing necessary library


In [ ]:
import numpy  as np
import pandas as pd
from skimage.transform import resize
from skimage.io import imread
import matplotlib.pyplot as plt
import os

In [ ]:
Categories = ["Normal","Tuberculosis"]
flat_data_arr = []
target_arr = []

In [ ]:
# importing dataset

In [ ]:
datadir = "/content/drive/MyDrive/Colab Notebooks/TB_Chest_Radiography_Database"

PRE-PROCESSING OF DATA

In [ ]:

for i in Categories:
    print(f"loading categories : {i}")
    path = os.path.join(datadir,i)
    for img in os.listdir(path):
        img_array = imread(os.path.join(path,img))
        img_resized = resize(img_array,(150,150,3))
        flat_data_arr.append(img_resized.flatten())
        target_arr.append(Categories.index(i))
    print(f"loaded category {i} ")

loading categories : Normal
loaded category Normal 
loading categories : Tuberculosis
loaded category Tuberculosis 


In [ ]:
flat_data = np.array(flat_data_arr)
target = np.array(target_arr)

In [ ]:
df = pd.DataFrame(flat_data)
df.shape
df["Target"] = target
target
df["Target"]

0       0
1       0
2       0
3       0
4       0
       ..
1908    1
1909    1
1910    1
1911    1
1912    1
Name: Target, Length: 1913, dtype: int64

In [ ]:
df.head()

0         1         2         3         4         5         6  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.447807  0.447807  0.447807  0.170672  0.170672  0.170672  0.055906   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.014996  0.014996  0.014996  0.014605  0.014605  0.014605  0.012210   
4  0.293618  0.293618  0.293618  0.257131  0.257131  0.257131  0.179046   

          7         8         9  ...     67491     67492     67493     67494  \
0  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
1  0.055906  0.055906  0.032936  ...  0.008877  0.008877  0.008877  0.078936   
2  0.000000  0.000000  0.000000  ...  0.108247  0.108247  0.108247  0.172464   
3  0.012210  0.012210  0.010970  ...  0.046492  0.046492  0.046492  0.047976   
4  0.179046  0.179046  0.030807  ...  0.879691  0.879691  0.879691  0.877456   

      67495     67496     67497     67498     67499  Target  
0  0.000000  0.000000  0.000000  0.000000  0.000000       0  
1  0.078936  0.078936  0.340733  0.340733  0.340733       0  
2  0.172464  0.172464  0.318892  0.318892  0.318892       0  
3  0.047976  0.047976  0.050983  0.050983  0.050983       0  
4  0.877456  0.877456  0.841489  0.841489  0.841489       0  

[5 rows x 67501 columns]

In [ ]:
X = df.drop('Target',axis=1)

In [ ]:
X.head()

0         1         2         3         4         5         6      \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.447807  0.447807  0.447807  0.170672  0.170672  0.170672  0.055906   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.014996  0.014996  0.014996  0.014605  0.014605  0.014605  0.012210   
4  0.293618  0.293618  0.293618  0.257131  0.257131  0.257131  0.179046   

      7         8         9      ...     67490     67491     67492     67493  \
0  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
1  0.055906  0.055906  0.032936  ...  0.001148  0.008877  0.008877  0.008877   
2  0.000000  0.000000  0.000000  ...  0.112638  0.108247  0.108247  0.108247   
3  0.012210  0.012210  0.010970  ...  0.046480  0.046492  0.046492  0.046492   
4  0.179046  0.179046  0.030807  ...  0.880600  0.879691  0.879691  0.879691   

      67494     67495     67496     67497     67498     67499  
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1  0.078936  0.078936  0.078936  0.340733  0.340733  0.340733  
2  0.172464  0.172464  0.172464  0.318892  0.318892  0.318892  
3  0.047976  0.047976  0.047976  0.050983  0.050983  0.050983  
4  0.877456  0.877456  0.877456  0.841489  0.841489  0.841489  

[5 rows x 67500 columns]

In [ ]:
import os
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from sklearn.metrics import accuracy_score

In [ ]:
Y = df[['Target']]
Y.head()

Target
0       0
1       0
2       0
3       0
4       0

In [ ]:


from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y)
X_train = X_train[:700]
y_train = y_train[:700]
X_test = X_test[:700]
y_test = y_test[:700]
# USING SVM
svc = svm.SVC(probability=True)
svc.fit(X_train,y_train)
print(f" SUPPORT VECTOR MACHINE ACCURACY {svc.score(X_test,y_test)}")

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


 SUPPORT VECTOR MACHINE ACCURACY 0.9603340292275574


In [ ]:
import time


In [ ]:
start_train= time.time()
svc.fit(X_train,y_train)
end_train =time.time()
start_test= time.time()
y_pred_train= svc.predict(X_train)
end_test= time.time()
y_pred_test= svc.predict(X_test)
print(f"Train_time: {end_train-start_train}, Test_time: {end_test-start_test}")

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train_time: 65.50901985168457, Test_time: 20.33192539215088


In [ ]:
X_train.shape

(700, 67500)

In [ ]:
svc.predict(X_test)

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

USING KNN

In [ ]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
print(f" KNN  ACCURACY {knn.score(X_test,y_test)}")

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


 KNN  ACCURACY 0.9373695198329853


In [ ]:
import time

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
start_train= time.time()
knn.fit(X_train,y_train)
end_train =time.time()
start_test= time.time()
y_pred_train= knn.predict(X_train)
end_test= time.time()
y_pred_test= knn.predict(X_test)
print(f"Train_time: {end_train-start_train}, Test_time: {end_test-start_test}")


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Train_time: 0.4235987663269043, Test_time: 2.780484437942505


In [ ]:
knn.predict(X_test)

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [ ]:
#USING DECISION TREE

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
print(f" Decision Tree accuracy {dt.score(X_test,y_test)}")

In [ ]:
start_train= time.time()
dt.fit(X_train,y_train)
end_train =time.time()
start_test= time.time()
y_pred_train= dt.predict(X_train)
end_test= time.time()
y_pred_test= dt.predict(X_test)
print(f"Train_time: {end_train-start_train}, Test_time: {end_test-start_test}")

Train_time: 33.76051306724548, Test_time: 0.4654519557952881


In [ ]:
dt.predict(X_test)

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,

In [ ]:
# USING RANDOM FOREST CLASSIFIER

In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
print(f"Random Forest accuracy : {rf.score(X_test,y_test)}")

<ipython-input-33-d5bd652587c7>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train,y_train)


Random Forest accuracy : 0.9331941544885177


In [ ]:
start_train= time.time()
rf.fit(X_train,y_train)
end_train =time.time()
start_test= time.time()
y_pred_train= rf.predict(X_train)
end_test= time.time()
y_pred_test= rf.predict(X_test)
print(f"Train_time: {end_train-start_train}, Test_time: {end_test-start_test}")

<ipython-input-34-1bdb2062f13e>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train,y_train)


Train_time: 9.83989143371582, Test_time: 0.8883099555969238


In [ ]:
rf.predict(X_test)

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,